config/routes.rb
Rails.application.routes.draw do
  root :to => 'beautiful#dashboard'
  match ':model_sym/select_fields' => 'beautiful#select_fields', as: :select_fields, via: [:get, :post]

  concern :bs_routes do
    collection do
      post :batch
      get  :treeview
      match :search_and_filter, action: :index, as: :search, via: [:get, :post]
    end
    member do
      post :treeview_update
    end
  end

  # Add route with concerns: :bs_routes here # Do not remove
  resources :products, concerns: :bs_routes
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/product.rb
class Product < ApplicationRecord

  include DefaultSortingConcern
  include FulltextConcern
  include CaptionConcern

  cattr_accessor :fulltext_fields do
    ["description"]
  end

  def self.permitted_attributes
    return :visible,:name,:price,:tva,:description_typetext,:description,:visible
  end

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "description", "description_fulltext", "description_typetext", "id", "name", "price", "tva", "updated_at", "visible"]
  end

end

app/controllers/products_controller.rb
# encoding : utf-8


class ProductsController < BeautifulController

  before_action :load_product, :only => [:show, :edit, :update, :destroy]

  # Uncomment for check abilities with CanCan
  #authorize_resource

  def index
    session['fields'] ||= {}
    session['fields']['product'] ||= (Product.columns.map(&:name) - ["id"])[0..4]
    do_select_fields('product')
    do_sort_and_paginate('product')

    @q = Product.ransack(
      params[:q]
    )

    @product_scope = @q.result(
      :distinct => true
    ).sorting(
      params[:sorting]
    )

    @product_scope_for_scope = @product_scope.dup

    unless params[:scope].blank?
      @product_scope = @product_scope.send(params[:scope])
    end

    @products = @product_scope.paginate(
      :page => params[:page],
      :per_page => 20
    ).to_a

    respond_to do |format|
      format.html{
        render
      }
      format.json{
        render :json => @product_scope.to_json(methods: :caption)
      }
      format.csv{
        require 'csv'
        csvstr = CSV.generate do |csv|
          csv << Product.attribute_names
          @product_scope.to_a.each{ |o|
            csv << Product.attribute_names.map{ |a| o[a] }
          }
        end
        render :plain => csvstr
      }
      format.xml{
        render :xml => @product_scope.to_a
      }
      format.pdf{
        pdfcontent = PdfReport.new.to_pdf(Product,@product_scope)
        send_data pdfcontent
      }
    end
  end

  def show
    respond_to do |format|
      format.html{
        render
      }
      format.json { render :json => @product }
    end
  end

  def new
    @product = Product.new

    respond_to do |format|
      format.html{
        render
      }
      format.json { render :json => @product }
    end
  end

  def edit

  end

  def create
    @product = Product.new(params_for_model)

    respond_to do |format|
      if @product.save
        format.html {
          if params[:mass_inserting] then
            redirect_to products_path(:mass_inserting => true)
          else
            redirect_to product_path(@product), :flash => { :notice => t(:create_success, :model => "product") }
          end
        }
        format.json { render :json => @product, :status => :created, :location => @product }
      else
        format.html {
          if params[:mass_inserting] then
            redirect_to products_path(:mass_inserting => true), :flash => { :error => "#{t(:error, default: "Error")} : #{@product.errors.full_messages.join(", ")}" }
          else
            render :action => "new"
          end
        }
        format.json { render :json => @product.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update

    respond_to do |format|
      if @product.update(params_for_model)
        format.html { redirect_to product_path(@product), :flash => { :notice => t(:update_success, :model => "product") }}
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @product.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :ok }
    end
  end

  def batch
    attr_or_method, value = params[:actionprocess].split(".")

    @products = []

    Product.transaction do
      if params[:checkallelt] == "all" then
        # Selected with filter and search
        do_sort_and_paginate(:product)

        @products = Product.ransack(
          session['search']['product']
        ).result(
          :distinct => true
        )
      else
        # Selected elements
        @products = Product.find(params[:ids].to_a)
      end

      @products.each{ |product|
        if not Product.columns_hash[attr_or_method].nil? and
               Product.columns_hash[attr_or_method].type == :boolean then
         product.update_attribute(attr_or_method, boolean(value))
         product.save
        else
          case attr_or_method
          # Set here your own batch processing
          # product.save
          when "destroy" then
            product.destroy
          when "touch" then
            product.touch
          end
        end
      }
    end

    redirect_to products_url
  end

  def treeview

  end

  def treeview_update
    modelclass = Product
    foreignkey = :product_id


    if update_treeview(modelclass, foreignkey)
      head :ok
    else
      head :internal_server_error
    end
  end

  private

  def load_product
    @product = Product.find(params[:id])
  end

  def params_for_model
    params.require(:product).permit(Product.permitted_attributes)
  end
end

app/helpers/products_helper.rb
# encoding : utf-8
require "beautiful_helper"


module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% @product.errors.full_messages.each do |msg| %><li><%= msg %></li><% end %>
      </ul>
    </div>
  <% end %>
      <div class="form-group">
      <%= f.label :name, t('app.models.product.bs_attributes.name', :default => 'name').capitalize, :class => "control-label" %>
      <%= f.text_field :name, :class => "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :price, t('app.models.product.bs_attributes.price', :default => 'price').capitalize, :class => "control-label" %>
      <div class="input-group">
        <span class="input-group-text">$</span><%= f.text_field :price, :class => "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :tva, t('app.models.product.bs_attributes.tva', :default => 'tva').capitalize, :class => "control-label" %>
      <%= f.text_field :tva, :class => "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :description, t('app.models.product.bs_attributes.description', :default => 'description').capitalize, :class => "control-label" %>
      <%= f.text_area :description, :class => "wysiwyg-editor form-control" %>
    </div>
    <%= f.hidden_field :description_typetext, :value => "html"  %>
    <div class="form-group">
      <%= f.label :visible, t('app.models.product.bs_attributes.visible', :default => 'visible').capitalize, :class => "control-label" %>
      <%= f.check_box :visible, :class => "form-control" %>
    </div>
<!-- Beautiful_scaffold - AddField - Do not remove -->
  <div>
    <%= link_to products_path, :class => "btn btn-light" do %>
      <i class="fa fa-chevron-left"></i> <%= t(:back, :default => "Back") %>
    <% end %>
    <%= f.submit :class => "btn btn-primary", :data => { :disable_with => t(:saving, :default => "Saving...") } %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h2><%= t(:editing, :default => 'Editing') %> <%= t('app.models.product.bs_caption', :default => 'product') %></h2>

<%= render 'form' %>

app/views/products/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md">
      <h2 class="title-index"><%= t(:listing, :default => "Listing") %> <%= t('app.models.product.bs_caption_plural', :default => 'product') %></h2>
      <p>
        <%= link_to '<i class="fa fa-plus"></i> '.html_safe + t(:new, :default => "New") + ' ' + t('app.models.product.bs_caption', :default => 'product'), new_product_path, :class => "btn btn-outline-secondary" %>
        <% if Product.columns.map(&:name).include?("product_id") %>
          <%= link_to '<i class="fa fa-folder-close"></i> '.html_safe + t(:treeview, :default => "Treeview") + ' ' + t('app.models.product.bs_caption', :default => 'product'), treeview_products_path, :class => "btn btn-outline-secondary" %>
        <% end %>
      </p>
    </div>
  </div>
</div>

<%= render :partial => "layouts/mass_inserting", :locals => { :engine => '', :namespace => '', :model_name => 'product', :model_columns => ['name','price','tva','description','visible'] } %>

<%# Set your scopes below (string in array) %>
<% scopes = [] %>
<% if !scopes.blank? %>
<div class="container-fluid mb-3" id="scopes-div" data-present-title="<%= t(:help_scope, :default => "Filter by scope") %>" data-present-description="<%= t(:help_scope_description, :default => "Filter by scope") %>" data-present-order="1">
  <div class="row">
    <div class="col-md btn-toolbar">
      <div class="btn-group">
        <%= link_to "All (#{@product_scope_for_scope.count})", products_path(:scope => ""), :class => "btn btn-outline-secondary #{((session[:scope][:product].to_s == '') ? 'active' : '')}" %>
        <% for scope in scopes %>
        <%= link_to "#{scope} (#{@product_scope_for_scope.send(scope).count})", products_path(:scope => scope), :class => "btn btn-outline-secondary #{((session[:scope][:product].to_s == scope) ? 'active' : '')}" %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<% end %>

<div class="container-fluid">
<div class="row">
  <div class="col-md-9">
    <%= form_tag  batch_products_path do %>
      <div class="card card-body bg-light mb-3">
        <div class="row">
          <div class="form-inline col-md" id="batch-div" data-present-title="<%= t(:help_batch, :default => "Batch processing") %>" data-present-description="<%= t(:help_batch_description, :default => "Batch processing description") %>" data-present-order="2">
            <label class="control-label mb-2 mr-sm-2" for="select01"><%= t(:batch, :default => "Batch") %></label>

            <select id="select01" name="actionprocess" class="custom-select mb-2 mr-sm-2">
              <option value="destroy"><%= t(:destroy, :default => "Destroy") %></option>
              <option value="touch"><%= t(:touch, :default => "Touch") %></option>
                        <option value="visible.true"><%= t(:settrueforattr, :attr => "'visible'", :default => "Set visible to true") %></option>
          <option value="visible.false"><%= t(:setfalseforattr, :attr => "'visible'", :default => "Set visible to false") %></option>

              <!-- Beautiful_scaffold - AddField - Batch - Do not remove -->
            </select>
            <button class="btn btn-outline-secondary mb-2 mr-sm-2" type="submit"><i class="fa fa-ok"></i> <%= t(:process, :default => "Process") %></button>
          </div>
          <div class="col-md">
            <a class="btn btn-xs btn-light float-right" id="hide-search-btn">
              <i class="fa fa-caret-right"></i>
              <i class="fa fa-caret-right"></i>
            </a>
            <a class="btn btn-xs btn-light float-right" id="show-search-btn">
              <i class="fa fa-caret-left"></i>
              <i class="fa fa-caret-left"></i>
            </a>
          </div>
        </div>
      </div>

      <%= render :partial => "layouts/modal_columns", :locals => { :engine_name => '', :model_name => "product", :model_columns => ['name','price','tva','description','visible','created_at','updated_at'] } %>

      <table class="table table-striped table-bordered table-sm">
        <thead>
          <tr>
            <th class="ac">
              <a class="" data-toggle="modal" href="#modal-columns" title="<%= t(:select_columns, :default => "Select Columns") %>" ><i class="fa fa-th-list"></i></a>
            </th>
            <th id="checkall-div" data-present-title="<%= t(:help_checkall, :default => "Check all elements") %>" data-present-description="<%= t(:help_checkall_description, :default => "Check all elements visible on the page") %>" data-present-order="3">
              <%= check_box_tag :checkall, '' %>
            </th>
            <th <%= visible_column("product", "name") %> class="bs-col-name">
              <%= sorting_header("product", "name", "") %>
            </th>
            <th <%= visible_column("product", "price") %> class="bs-col-price">
              <%= sorting_header("product", "price", "") %>
            </th>
            <th <%= visible_column("product", "tva") %> class="bs-col-tva">
              <%= sorting_header("product", "tva", "") %>
            </th>
            <th <%= visible_column("product", "description") %> class="bs-col-description">
              <%= sorting_header("product", "description", "") %>
            </th>
            <th <%= visible_column("product", "visible") %> class="bs-col-visible">
              <%= sorting_header("product", "visible", "") %>
            </th>

            <!-- Beautiful_scaffold - AddField - Header - Do not remove -->
            <th <%= visible_column("product", "created_at") %> class="bs-col-created_at">
              <%= sorting_header("product", "created_at", "") %>
            </th>
            <th <%= visible_column("product", "updated_at") %> class="bs-col-updated_at">
              <%= sorting_header("product", "updated_at", "") %>
            </th>
            <th colspan="3">
              <label class="checkbox mb-0" id="checkallall-div" data-present-title="<%= t(:help_checkallall, :default => "Check all elements") %>" data-present-description="<%= t(:help_checkallall_description, :default => "Check all elements, that match current filter even if they are not visible on the page") %>" data-present-order="4">
                <%= check_box_tag :checkallelt, 'all' %>
                <%= pluralize(@product_scope.count, t('app.models.product.bs_caption', :default => 'product'), t('app.models.product.bs_caption_plural', :default => 'product')) %>
              </label>
            </th>
          </tr>
        </thead>
        <tbody>
          <% @products.each do |product| %>
          <tr class="line-<%= cycle("1","2") %>">
            <td class="ar"><%= product.id %></td>
            <td><%= check_box_tag "ids[]",product.id, false, :class => 'cbbatch' %></td>
            <td <%= visible_column("product", "name") %> class="bs-col-name <%= align_attribute("string") %>">
                <%= product.name %>
            </td>
            <td <%= visible_column("product", "price") %> class="bs-col-price <%= align_attribute("price") %>">
                <%= number_to_currency(product.price, :locale => I18n.locale) %>
            </td>
            <td <%= visible_column("product", "tva") %> class="bs-col-tva <%= align_attribute("float") %>">
                <%= product.tva %>
            </td>
            <td <%= visible_column("product", "description") %> class="bs-col-description <%= align_attribute("wysiwyg") %>">
                <%= product.description %>
            </td>
            <td <%= visible_column("product", "visible") %> class="bs-col-visible <%= align_attribute("boolean") %>">
                <%= t((product.visible ? "yes" : "no").to_sym) %>
            </td>
<!-- Beautiful_scaffold - AddField - Column - Do not remove -->
            <td <%= visible_column("product", "created_at") %> class="bs-col-created_at <%= align_attribute("datetime") %>">
              <%= l(product.created_at, :format => :long) %>
            </td>
            <td <%= visible_column("product", "updated_at") %> class="bs-col-updated_at <%= align_attribute("datetime") %>">
              <%= l(product.updated_at, :format => :long) %>
            </td>
            <td class="ac am"><%= link_to '<i class="fa fa-search"></i>'.html_safe, product_path(product), :title => t(:show, :default => "Show") %></td>
            <td class="ac am"><%= link_to '<i class="fa fa-edit"></i>'.html_safe, edit_product_path(product), :title => t(:edit, :default => "Edit") %></td>
            <td class="ac am"><%= link_to '<i class="fa fa-times"></i>'.html_safe, product_path(product), :data => { :confirm => t(:are_you_sure, :default => "Are you sure?") }, :method => :delete, :title => t(:destroy, :default => "Destroy") %></td>
          </tr>
          <% end %>
        </tbody>
      </table>

      <div class="btn-toolbar">
        <div class="btn-group">
          <% clean_params %>
          <%= will_paginate @products,
                  :inner_window => 0,
                  :outer_window => 0,
                  :previous_label => t(:prev, :default => "Previous"),
                  :next_label => t(:next, :default => "Next"),
                  :renderer => WillPaginate::ActionView::BootstrapLinkRenderer
          %>

        </div>
        <div class="btn-group btn-group-sm float-right">
          <%= link_to '<i class="fa fa-download"></i> CSV'.html_safe,  products_path(:format => :csv), :class => "btn btn-outline-secondary" %>
          <%= link_to '<i class="fa fa-download"></i> XML'.html_safe,  products_path(:format => :xml), :class => "btn btn-outline-secondary" %>
          <%= link_to '<i class="fa fa-download"></i> JSON'.html_safe, products_path(:format => :json), :class => "btn btn-outline-secondary" %>
          <%= link_to '<i class="fa fa-download"></i> PDF'.html_safe,  products_path(:format => :pdf), :class => "btn btn-outline-secondary" %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-md-3">
    <%= search_form_for @q, :url => search_products_path, :html => { :class => "card bg-light mb-3 search-and-filter" }, :method => :post do |f| %>
      <div class="card-header"><%= t("search_and_filter", :default => "Search & filter") %></div>
      <div class="card-body">
        <div class="card-text">
                <%= ransack_field("product", "name", f, "Name") %>
      <%= ransack_field("product", "price", f, "Price") %>
      <%= ransack_field("product", "tva", f, "Tva") %>
      <%= ransack_field("product", "description", f, "Description") %>
      <%= ransack_field("product", "visible", f, "Visible") %>

          <!-- Beautiful_scaffold - AddField - Search - Do not remove -->
          <div class="panel-group">
            <div class="panel panel-default">
              <div class="panel-heading">
                <a class="badge badge-light accordion-toggle" data-toggle="collapse-next">
                  <%= t(:more_options, :default => "More options...") %>
                </a>
              </div>
              <div class="panel-collapse collapse">
                <div class="panel-body">
                                <%= ransack_field("product", "created_at", f, "Created At") %>
              <%= ransack_field("product", "updated_at", f, "Updated At") %>
              <%= ransack_field("product", "id", f, "Id") %>

                </div>
              </div>
            </div>
          </div>
          <%= f.submit t(:filter, :default => "Filter"), :class => "btn btn-primary btn-sm btn-block" %>
          <%= link_to  t(:cancel, :default => "Cancel"), products_path(:nosearch => "ok"), :class => "btn btn-light btn-sm btn-block" %>
        </div>
      </div>
    <% end %>
  </div>
</div>
</div>

app/views/products/new.html.erb
<h2><%= t(:new, :default => 'New') %> <%= t('app.models.product.bs_caption', :default => 'product') %></h2>

<%= render 'form' %>

app/views/products/show.html.erb
<h2><%= t(:show, :default => "Show") %> <%= t('app.models.product.bs_caption', :default => 'product') %></h2>

  <p>
    <b><%= t('app.models.product.bs_attributes.name', :default => 'name') %>:</b>
      <%= @product.name %>
  </p>
  <p>
    <b><%= t('app.models.product.bs_attributes.price', :default => 'price') %>:</b>
      <%= number_to_currency(@product.price) %>
  </p>
  <p>
    <b><%= t('app.models.product.bs_attributes.tva', :default => 'tva') %>:</b>
      <%= @product.tva %>
  </p>
  <p>
    <b><%= t('app.models.product.bs_attributes.description', :default => 'description') %>:</b>
      <%= @product.description %>
  </p>
  <p>
    <b><%= t('app.models.product.bs_attributes.visible', :default => 'visible') %>:</b>
      <%= t((@product.visible ? "yes".to_sym : "no".to_sym)) %>
  </p>

<!-- Beautiful_scaffold - AddField - Field - Do not remove -->

<%= link_to t(:edit, :default => "Edit"), edit_product_path(@product), :class => "btn btn-light" %>
<%= link_to t(:back, :default => "Back"), products_path, :class => "btn btn-light" %>

app/views/products/treeview.html.erb
<h2><%= t(:treeview, :default => 'Treeview') %> <%= t('app.models.product.bs_caption', :default => 'product') %></h2>



<%
engine_name       = ""
namespace_for_url = ""
plural_model_name = "products"
model_name        = "product"
opened_node       = Product.select(:id).all.map{ |g| "'treeelt_" + g.id.to_s + "'" }.join(',').html_safe
%>

<div id="treeview" data-model="<%= model_name %>" data-url="/<%= engine_name %><%= namespace_for_url %><%= plural_model_name %>/" data-opened="[<%= opened_node %>]">
  <ul>
    <% Product.transaction do %>
    <% ar = Product.where(:product_id => nil) %>
    <% ar = ar.order("position") if Product.column_names.include?("position") %>
      <% for g in ar.all %>
        <%= build_treeview(g, 'products') %>
      <% end %>
    <% end %>
  </ul>
</div>