config/routes.rb
Rails.application.routes.draw do
  root :to => 'beautiful#dashboard'
  match ':model_sym/select_fields' => 'beautiful#select_fields', as: :select_fields, via: [:get, :post]

  concern :bs_routes do
    collection do
      post :batch
      get  :treeview
      match :search_and_filter, action: :index, as: :search, via: [:get, :post]
    end
    member do
      post :treeview_update
    end
  end

  # Add route with concerns: :bs_routes here # Do not remove
  resources :products, concerns: :bs_routes
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/_beautiful_menu.html.erb
<!-- Beautiful Scaffold Menu Do Not Touch This -->
<%= link_to t('app.models.product.bs_caption_plural', :default => 'product').capitalize, products_path, class: "nav-link #{(params[:controller] == "products" ? "active" : "")}" %>

app/views/layouts/_form_habtm_tag.html.erb
<%#=
  render :partial => "layouts/form_habtm_tag", :locals => {
    :model_class => @product,
    :model_name => "product",
    :plural_model_name => "products",
    :linked_model_name => "tag",
    :plural_linked_model_name => "tags",
    :namespace_bs => "admin",
    :engine_bs => "YOUR_ENGINE_OR_EMPTY_STRING",
    :field_to_search_for_linked_model => "name",
    :attr_to_show => "caption",
    :f => f
  }
  # Example to put in a _form.html.erb
%>
<% path_namespace = "/" %>
<% path_namespace += "#{engine_bs}/" if engine_bs.present? %>
<% path_namespace += "/#{namespace_bs}/" if namespace_bs.present? %>

<div class="form-group">
    <%= f.label plural_linked_model_name.to_sym, t(plural_linked_model_name.to_sym, :default => plural_linked_model_name.capitalize), :class => "control-label" %>
    <div>
        <select multiple="multiple" class="form-control bs-tagit" id="<%= model_name %>_<%= linked_model_name %>_ids" name="<%= model_name %>[<%= linked_model_name %>_ids][]"  data-tags="true" data-placeholder="<%= t('select-an-option', default: 'Select an option') %>" data-allow-clear="true" data-ajax--cache="true" data-ajax--url="<%= path_namespace %><%= plural_linked_model_name %>/search_and_filter.json" data-param="q[<%= field_to_search_for_linked_model %>_cont]" data-result="<%= attr_to_show %>">
          <% begin %>
            <% for elt in model_class.send(plural_linked_model_name) %>
            <option selected="selected" data-value="<%= elt.id %>"><%= elt.caption %></option>
            <% end %>
          <% rescue %>
          <% end %>
        </select>
    </div>
</div>

app/views/layouts/_mass_inserting.html.erb
<% model = ("#{(engine.blank? ? '' : "#{engine.camelize}::")}#{model_name.camelize}").constantize %>
<% formparams = [] %>
<% if !namespace.blank? %>
  <% formparams << namespace %>
<% end %>
<% formparams << model.new %>
<div class="container-fluid mb-3">
  <div class="row">
    <div class="col-md">
      <div class="card card-body bg-light">
        <%= form_for formparams, :method => :post, :html => { :class => "form-inline mass-inserting #{(params[:mass_inserting] ? 'setfocus' : '')}" } do |f| %>
          <%= hidden_field_tag :mass_inserting, true %>
          <% for col in model_columns %>
            <div <%= visible_column(model_name, col, 'inline') %> class="form-group mr-sm-2 col-<%= col %>">
              <%=
                ar = model.columns_hash[col]
                if !ar.nil?
                  case ar.type
                  when :integer then
                    if col =~ /.*_id/
                      f.collection_select((col).to_sym, col.camelize.constantize.all, :id, :caption, { :include_blank => true, :selected => (begin params[:q]["#{col}_eq"].to_i rescue '' end) }, {:class => "form-control"})
                    else
                      f.text_field(col.to_sym, :placeholder => t(i18n_translate_path(model_name, col), default: "#{model_name}.#{col}").capitalize, :class => "form-control")
                    end
                  when :boolean then
                    (
                    "<label class='bs-label-ib'>#{f.check_box(col.to_sym, {}, true, false)}#{t(i18n_translate_path(model_name, col), default: "#{model_name}.#{col}").capitalize}</label>".html_safe
                    )
                  else
                    f.text_field(col.to_sym, :placeholder => t(i18n_translate_path(model_name, col), default: "#{model_name}.#{col}").capitalize, :class => "form-control")
                  end
                else
                  f.collection_select(("#{false ? "#{engine}_" : ''}#{col}_id").to_sym, ("#{(engine.blank? ? '' : "#{engine.camelize}::")}#{col.camelize}").constantize.all, :id, :caption, { :include_blank => true, :selected => (begin params[:q]["#{col}_id_eq"].to_i rescue '' end) }, {:class => "form-control"})
                end
              %>
            </div>
          <% end %>
          <div class="form-group">
            <%= f.submit t(:create, :default => "Create"), :class => "btn btn-outline-secondary", :data => { :disable_with => t(:saving, :default => "Saving...") } %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_modal_columns.html.erb
<div class="modal fade" id="modal-columns">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"><%= t(:select_columns, :default => "Select Columns") %></h5>
        <button type="button" class="close" data-dismiss="modal">×</button>
      </div>
      <div class="modal-body">
        <% for field in model_columns %>
          <label class="checkbox">
            <input type="checkbox" name="field[]" value="<%= field %>" <%= "checked" if session['fields'][model_name.to_s].include?(field) %>> <%= t("app.models.#{model_name}.bs_attributes.#{field}", :default => field.capitalize) %>
          </label><br />
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" id="filter-columns" data-url="<%= select_fields_url(model_name) %>">Ok</button>
        <button type="button" class="btn btn-light" id="cancel-filter-columns"><%= t(:cancel, :default => "Cancel") %></button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestBeautifulScaffold</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/beautiful_layout.html.erb
<!DOCTYPE html>
<html lang="<%= (I18n.locale || I18n.default_locale) %>">
  <head>
    <meta charset="utf-8">
    <title>Beautiful Scaffold</title>

    <meta name="description" content="Beautiful Scaffold">
    <meta name="author" content="You or me Sylvain Claudel (https://blog.rivsc.ovh)">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!--TODO remove cdn-->
    <script src="https://unpkg.com/driver.js/dist/driver.min.js"></script>
    <link rel="stylesheet" href="https://unpkg.com/driver.js/dist/driver.min.css">

    <%= stylesheet_link_tag "application-bs" %>
    <%= javascript_include_tag "application-bs" %>

    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

    <%= csrf_meta_tags %>
    <%= yield :head %>
  </head>
  <body>
    <div class="navbar navbar-expand-md navbar-dark bg-dark">
      <div class="navbar-header">
        <a class="navbar-brand" href="#">
          Beautiful-Scaffold
        </a>
        <button type="button" class="navbar-toggler collapsed" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>
      <div class="navbar-collapse collapse">
        <nav class="nav navbar-nav">
          <a href="/" class="nav-link">Home</a>
          <%= render :partial => "layouts/beautiful_menu" %>
          <!-- Beautiful_scaffold - Signin - Do not remove -->
        </nav>
        <i class="fa fa-question-circle text-white float-right" id="bs-help"></i>
      </div>
    </div>
    <div class="container-fluid">
      <div class="row">
        <div class="col-md filler">
          <% if !flash[:notice].blank? %>
            <div class="alert alert-info">
              <a class="close" data-dismiss="alert" href="#">×</a>
              <h4 class="alert-heading">Info : </h4>
              <%= flash[:notice] %>
            </div>
          <% end %>
          <% if !flash[:alert].blank? %>
            <div class="alert alert-warning">
              <a class="close" data-dismiss="alert" href="#">×</a>
              <h4 class="alert-heading">Warning : </h4>
              <%= flash[:alert] %>
            </div>
          <% end %>
          <% if !flash[:error].blank? %>
            <div class="alert alert-danger">
              <a class="close" data-dismiss="alert" href="#">×</a>
              <h4 class="alert-heading">Error : </h4>
              <%= flash[:error] %>
            </div>
          <% end %>
          <div class="mt-2">
            <%= yield %>
          </div>
        </div>
      </div>
    </div>

    <div class="loader" style="display:none">
      <div class="circle"></div>
      <div class="circle1"></div>
    </div>

    <!-- Beautiful_scaffold - Modal - Do not remove -->

    <script type="text/javascript">
      <% if !@opened_modal.blank? %>
      $('<%= @opened_modal %>').modal('show');
      <% end %>
    </script>
  </body>
</html>